config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'

  #buildings
  get '/apartments/:apartment_id/buildings(.:format)', to:  'buildings#index',as: 'apartament_buildings'
  get '/apartments/:apartment_id/buildings/new(.:format)', to:  'buildings#new', as:  'new_apartment_building'
  get '/apartments/:apartment_id/buildings/:id/edit(.:format)', to: 'buildings#edit', as:  'edit_apartment_building'
  get '/apartments/:apartment_id/buildings/:id(.:format)',  to: 'buildings#show', as:   'apartment_building'


  #apartaments
  get '/apartments(.:format)', to:  'apartments#index', as: 'apartments'
  get '/apartments/new(.:format)', to:  'apartments#new', as: 'new_apartment'
  get '/apartments/:id/edit(.:format)', to: 'apartments#edit',  as: 'edit_apartment'
  get '/apartments/:id(.:format)', to:  'apartments#show',  as: 'apartment'
  
  #creador
  get '/creador', to: 'creador#programador', as: 'creador'
  
  
  resources :apartments 
  resources :buildings
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
  validate :no_duplicados
  validates(:numero, presence: true)
  #validates :numero, length: {maximum: 4,too_long: "%{count} characters is the maximum allowed" }
  validates(:building_id, presence: true)
  



  private
    def no_duplicados
    

    encontrados = self.building.apartment.select {|depto|
    depto.numero == self.numero
    }
      if encontrados.count > 1
        self.errors.add(:error_duplicado,"El departamento ingresado ya existe en la base de datos")
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

    has_many :apartment

    validates(:nombre, presence: true)
    #validates(:nombre, uniqueness: true)
    
    validates(:direccion, presence: true)
    #validates(:direccion, uniqueness: true)
    
    validates(:ciudad, presence: true)
    

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: %i[ show edit update destroy ]

  # GET /apartments or /apartments.json
  def index
    #@apartments = Apartment.all
    @apartments = Apartment.includes(:building).order(id: :asc)
  end

  # GET /apartments/1 or /apartments/1.json
  def show
    @apartments = Apartment.includes(:building).order(id: :asc)
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
    consultar_buildings
  end

  # GET /apartments/1/edit
  def edit
    consultar_buildings
  end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
      
        format.html { redirect_to @apartment, notice: "El departamento se creó correctamente." }
        format.json { render :show, status: :created, location: @apartment }
      else
        consultar_buildings
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        
        format.html { redirect_to @apartment, notice: "El departamento se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @apartment }
      else
        consultar_buildings
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: "El departamento fue eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:numero, :building_id)
    end

    def consultar_buildings
      @buildings = Building.select(:id, :nombre).order(nombre: :asc)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
    
  @buildings = Building.includes(:apartments).order(numero: :asc)

  
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format| 
      if @building.save
        format.html { redirect_to @building, notice: "El edificio fue creado con éxito." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: "El edificio se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "El edificio fue eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:nombre, :direccion, :ciudad)
    end
end

app/controllers/creador_controller.rb
class CreadorController <ApplicationController

    def creador
        
    end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
    # include ActiveModel::Model

    # attr_accessor :nombre
    # attr_accessor :direccion
    # attr_accessor :ciudad
    
    # validates(:nombre, presence: true)
    # validates(:direccion, presence: true)
    # validates(:ciudad, presence: true)
    
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment) do |form| %>
<div class="row justify-content-center">
  <div class="card" style="width: 18rem;">
    <div class="card-body">

      <% if apartment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

          <ul>
            <% apartment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :numero %>
        <%= form.text_field :numero %>
      </div>

      <div class="field">
        <%# form.label :building_id %>
        <%# form.text_field :building_id %>
      </div>

      <div>
        <%= form.label :building_id,"Edificio", class: "form-label" %>
          <% if apartment.building %>
            <%= form.select(:building_id, options_from_collection_for_select(buildings, :id, :nombre, apartment.building_id),  {class:'form-select'}) %>
          <% else %>
            <%= form.select(:building_id, options_from_collection_for_select(buildings, :id, :nombre),  {class:'form-select'}) %>
          <% end %>
      </div> 
  
  <br>

      <div class="actions">
        <%= form.submit  class:"btn btn-primary" %>
      </div>
    </div>
  </div>    
</div>
<% end %>

app/views/apartments/edit.html.erb
<br>
<h1 class="text-center">Editar Departamento</h1>

<%= render 'form', apartment: @apartment , buildings: @buildings%>

<%# link_to 'Mostrar', @apartment, class:"btn btn-primary" %> <br>
<br>
<div class="form-row text-center">
<%= link_to 'Volver', apartments_path, class:"btn btn-primary" %>
</div>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>
<div class="scrollWrapper">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Numero</th>
      <th>Id Edificio</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody height="500">
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.numero %></td>
        <td><%= apartment.building_id %></td>
        
        <td><%= link_to 'mostrar', apartment, class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_apartment_path(apartment), class:"btn btn-primary" %></td>
        <td><%= link_to 'Eliminar', apartment, method: :delete, data: { confirm: '¿Estas seguro de eliminar este departamento?' }, class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to  new_apartment_path, class:"btn btn-primary" do %>
<i class="bi bi-plus-square"></i>
Crear nuevo departamento
<% end %>

app/views/apartments/new.html.erb
<h1 class="text-center">Crear Departamento</h1>

<%= render 'form', apartment: @apartment, buildings: @buildings %>
<br>
<div class="form-row text-center">
<%= link_to 'Volver', apartments_path, class:"btn btn-primary" %>
</div>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <p>
      <strong>Numero:</strong>
      <%= @apartment.numero %>
    </p>

    <p>
      <strong>Edificio:</strong>
      <%= @apartment.building_id %>
    </p>





    <%# link_to 'Editar', edit_apartment_path(@apartment), class:"btn btn-primary" %> 
    <%= link_to 'Volver', apartments_path, class:"btn btn-primary" %>
  </div>
</div>
</div>


            

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
<div class="row justify-content-center">
  <div class="card" style="width: 18rem;">
    <div class="card-body">

    <% if building.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

        <ul>
          <% building.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :nombre %>
    </div>

    <div class="field">
      <%= form.label :direccion %>
      <%= form.text_field :direccion %>
    </div>

    <div class="field">
      <%= form.label :ciudad %>
      <%= form.text_field :ciudad %>
    </div>
  <br>
    <div class="actions">
      <%= form.submit  class:"btn btn-primary" %>
    </div>

    </div>
  </div>  
</div>
  
<% end %>

app/views/buildings/edit.html.erb
<br>
<h1 class="text-center">Editar Edificios</h1>

<%= render 'form', building: @building %>

<%# link_to 'Mostrar', @building, class:"btn btn-primary" %> 
<br>
<div class="form-row text-center">
<%= link_to 'Volver', buildings_path, class:"btn btn-primary" %>
</div>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edificios</h1>
<div class="scrollWrapper">
<table class="table table-striped">
  <thead>
    <tr>

      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Direccion</th>
      <th scope="col">Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody height="500">
    <% @buildings.each do |building| %>
      <tr>

        <td><%= building.id %></td>
        <td><%= building.nombre %></td>
        <td><%= building.direccion %></td>
        <td><%= building.ciudad %></td>
        <td><%= link_to 'Mostrar', building, class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_building_path(building), class:"btn btn-primary" %></td>
        <td><%= link_to 'Eliminar', building, method: :delete, data: { confirm: '¿estas seguro de eliminar este edificio?' }, class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to new_building_path, class:"btn btn-primary" do %>
<i class="bi bi-plus-square"></i>
Crear nuevo edificio

<% end %>

app/views/buildings/new.html.erb
<h1 class="text-center">Crear Edificio</h1>

<%= render 'form', building: @building %>
<br>
<div class="form-row text-center">
<%= link_to 'Back', buildings_path, class:"btn btn-primary" %>
</div>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" >
  <div class="card-body">
    
    
    <p>
      <strong><h4>Edificio <%= @building.nombre %></h4></strong>
      
    </p>

    <p>
      <strong>Direccion:</strong>
      <%= @building.direccion %>
    </p>

    <p>
      <strong>Ciudad:</strong>
      <%= @building.ciudad %>
    </p>

    
    
   
  </div>
</div>



  <%# @building.apartment.each do |apartments| %>
<div class="scrollWrapper">
    <table class="table table-striped">
  <thead>
    <tr>

      <th scope="col">Id</th>
      <th scope="col">Numero departamento</th>
      
      
    </tr>
  </thead>

  <tbody height="400">
    <% @building.apartment.each do |apartments| %>
      <tr>

        <td><%= apartments.id %></td>
        <td><%= apartments.numero %></td>
       
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
 <%= link_to 'Volver', buildings_path, class:"btn btn-primary" %>
                   
  <%# end %>

app/views/creador/programador.html.erb
<br>
<div class="row justify-content-center">
    
    <div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Claudio Leiva Ramos</h5>
        <hr>
        <h6 class="card-subtitle mb-2 text-muted"> Técnico en Informática </h6>
        <hr>
        <p class="card-text">App desarrollada con el fin de presentarla como examen final del curso "Emprendimiento Digital",
        impartido por Edutecno. <br>
        Esta app esta desarrollada para manejar departamentos dentro de distintos edificios.</p>
        <hr>
        <a href="https://github.com/ClaudioLeivaR" class="card-link">Visita mi Github</a>
    </div>
    </div>

</div>

app/views/layouts/_navbar.html.erb
<%# <nav class="nav nav-pills nav-fill" id="pills-tab" role="tablist">
  <a class="nav-link active" aria-current="page" href="/">Edificios</a>
  <a class="nav-link " href="/apartments">Departamentos</a>
  <a class="nav-link " href="/creador">Programador</a>
 
</nav>
<br><br> %>




<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><i class="bi bi-building"></i>Examen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/">Edificios</a>
        <a class="nav-link active" href="/apartments">Departamentos</a>
        <a class="nav-link active" href="/creador">Creador</a>
        
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edificios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
  </body>
</html>